pipeline {
    node('docker') {
        checkout scm
        stage('Build') {
            docker.image('maven:3.3.3').inside {
                sh 'mvn --version'
            }
        }
    }
    agent { docker 'maven:3.3.3' }
    stages {
        stage('build') {
            steps {
                sh 'mvn --version'
            }
        }
    }
}